version: '3.3'

networks:
  project-auth-network:
    driver: bridge

volumes:
  postgres-volume:
  prometheus_data:
  grafana_data:

services:
  project-auth-postgres-container:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: auth_project

    ports:
      - "5432:5432"
    networks:
      - project-auth-network
    restart: always
    volumes:
    - ./postgres-volume:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - project-auth-network
    ports:
      - "9090:9090"
    restart: always
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - project-auth-network
    ports:
      - "3000:3000"
    restart: always
